# run the test suite
tests:
    image: registry.gitlab.lis-lab.fr:5005/dev/multiview_generator/ubuntu:18.04
    tags:
        - docker
    script:
        - python3 setup.py install
        - pytest-3
    coverage: '/^TOTAL.+?(\d+\%)$/'
    artifacts:
        paths:
            - htmlcov/

# generate the documentation
doc:
    image: registry.gitlab.lis-lab.fr:5005/dev/multiview_generator/ubuntu:18.04
    tags:
        - docker
    only:
        - master
    script:
        - export LC_ALL=$(locale -a | grep en_US)
        - export LANG=$(locale -a | grep en_US)
        - pip3 install -e .[doc]
        - sphinx-apidoc -o docs/source multiview_generator
        - sphinx-build -b html docs/source docs/build/html && python docs/source/post_build_clean.py
        - cp -r ./docs/build public
    artifacts:
        paths:
          - public


# TODO: Replace the task doc by the following task pages when making the
# project public
#
pages:
    image: registry.gitlab.lis-lab.fr:5005/dev/multiview_generator/ubuntu:18.04
    tags:
        - docker
    only:
        - master
    script:
        - export LC_ALL=$(locale -a | grep en_US)
        - export LANG=$(locale -a | grep en_US)
        - pip3 install -e .[doc]
        - sphinx-apidoc -o docs/source multiview_generator
        - sphinx-build -b html docs/source docs/build/html && python docs/source/post_build_clean.py
        - cp -r ./docs/build public
    artifacts:
        paths:
          - public
