# run the test suite
tests:
    image: python:3.11 
    tags:
        - docker
    script:
        - pip3 install numpy
        - pip3 install .
        - pip3 install .[dev]
        - python3 -m pytest
    coverage: '/^TOTAL.+?(\d+\%)$/'
    artifacts:
        paths:
            - htmlcov/

# generate the documentation
doc:
    image: python:3.11 
    tags:
        - docker
    only:
        - master
    script:
        - pip3 install numpy
        - export LC_ALL=$(locale -a | grep en_US)
        - export LANG=$(locale -a | grep en_US)
        - pip3 install -e .[doc]
        - sphinx-apidoc -o docs/source multiview_generator
        - sphinx-build -b html docs/source docs/build/html && python docs/source/post_build_clean.py
        - cp -r ./docs/build public
    artifacts:
        paths:
          - public


# TODO: Replace the task doc by the following task pages when making the
# project public
#
pages:
    image: python:3.11 
    tags:
        - docker
    only:
        - master
    script:
        - pip3 install numpy
        - export LC_ALL=$(locale -a | grep en_US)
        - export LANG=$(locale -a | grep en_US)
        - pip3 install -e .[doc]
        - sphinx-apidoc -o docs/source multiview_generator
        - sphinx-build -b html docs/source docs/build/html && python docs/source/post_build_clean.py
        - cp -r ./docs/build public
    artifacts:
        paths:
          - public
