n_views: 4
n_classes: 3
confusion_matrix:
  - [0.4, 0.4, 0.4, 0.4]
  - [0.55, 0.4, 0.4, 0.4]
  - [0.4, 0.5, 0.52, 0.55]
#  - [0.4, 0.5, 0.5, 0.4]
#  - [0.4, 0.4, 0.4, 0.4]
#  - [0.4, 0.4, 0.4, 0.4]
#  - [0.4, 0.4, 0.4, 0.4]
#  - [0.4, 0.4, 0.4, 0.4]
n_samples: 2000
n_features: 3
n_informative: 3
class_seps: 10
class_weights: [0.125, 0.125, 0.125,]# 0.125, 0.125, 0.125, 0.125, 0.125,]
mutual_error: 0.2
redundancy: 0.1
complementarity: 0.35
name: "doc_summit"
sub_problem_type: ["base", "base", "base", "gaussian"]
