name: Deploy Sphinx docs to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install Pandoc
        uses: pandoc/actions/setup@v1
        with:
         version: '2.4'

      - name: Install dependencies
        run: |
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          pip3 install --upgrade setuptools wheel packaging
          pip3 install sphinx>=1.8  numpydoc  sphinx_gallery matplotlib jupyter
          pip3 install nbsphinx nbsphinx_link sphinx_rtd_theme sphinx-autoapi
          pip3 install summit-multi-learn==0.0.2
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
          pip3 install -e .[doc]  --no-build-isolation --use-pep517
          sphinx-apidoc -o docs/source   multiview_generator

      - name: Build docs
        run: |
            sphinx-build -b html docs/source docs/build && python docs/source/post_build_clean.py

      - name: Check contents of build directory
        run: |
          echo "Listing docs/build:"
          ls -l docs/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          publish_branch: gh-pages
          force_orphan: true
